version: '2.1'
orbs:
  slack: circleci/slack@4.1.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.18

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run lint
      - run: npm test -- --max-workers=2
      - slack/notify:
          event: fail
          template: SLACK_FAIL_TEST_TEMPLATE
      - slack/notify:
          event: pass
          template: SLACK_PASS_TEST_TEMPLATE

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.18

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run build:badge
      - run: npm run upload_badge
      - slack/notify:
          event: fail
          template: SLACK_FAIL_TEMPLATE
      - slack/notify:
          event: pass
          template: SLACK_PASS_TEMPLATE

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          context:
            - slack-secrets
          filters:
            tags:
              only: /^badge-v.*-(stage|prod)$/
      - deploy:
          context:
            - slack-secrets
          filters:
            tags:
              only: /^badge-v.*-(stage|prod)$/
            branches:
              ignore: /.*/
          requires:
            - test
